services:
  apaw-user:
    build: .
    image: apaw-user:latest
    restart: always
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/apawuserdb
    networks:
      - apawnet

networks:
  apawnet:
    external: true

#> docker compose up --build -d
