spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/dbapawuser}
    username:  ${POSTGRES_URL:postgres}
    password:  ${POSTGRES_URL:postgres}
