spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

eureka:
  client:
    service-url:
      defaultZone: http://apaw-eureka:8761/eureka/

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

app:
  hosting: AWS
