spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres-server:5432/apawuserdb
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
